### ISSUE TITLE
exiftool gem dependency not required

### ISSUE THREAD

**Issue by elsurudo** [exiftool-rb/exiftool_vendored.rb#1]
As far as I can see, the dependency on the "exiftool" gem is main a convenience, since that gem isn't used by this one.

I realize that using the "exiftool" gem is the main use-case for this gem, but dropping the dependency (and instead simply requiring both in your Gemfile) makes this gem more flexible. I need it, for example, only to vendor in the exiftool oerl lib, but have my own "wrapper" for it. So the dependency on "exiftool" is just dead-weight to me.

**Comment by jrochkind** [comment]
I am here too, but I'm not sure the unneeded exiftool dependency matters enough to motivate me to PR. Thanks for the gem!

**Comment by jrochkind** [comment]
Hey this is actually a pretty simple PR, I could make it -- but it would be backwards incompatible in that anyone who has `exiftool_vendored` in their Gemfile but not `exiftool`, but has been using the `exiftool` anyway -- will need to add `exiftool` itself to their gemfile. (Just that). 

If that would still be considered for a PR, I'll make it! @morozgrafix ? Thanks for the gem, and for keeping releases up to date with new exiftool releases!

**Comment by morozgrafix** [comment]
@jrochkind it has been a while since I looked under the hood of this gem, with exception of maintenance releases whenever exiftool rolls up to a new version. I believe that `exiftool` is required in this file: https://github.com/exiftool-rb/exiftool_vendored.rb/blob/master/lib/exiftool_vendored.rb#L3

Ideally I would like to see a non-breaking change in terms of the backwards compatibility. I think over the years people who are using the gem are used to backwards compatibility with stable version rollup updates. 

On one hand this is a 6 year old issue and we haven't had many complaints about it, on the other - PRs with improvements are always welcome. Let me know if you want me to reopen this issue and you'd like to take a stab at it.

**Comment by morozgrafix** [comment]
Thanks for the details. I think I would prefer leaving it as is. Given that `exiftool` wrapper gem is 6.5KB it doesn't really bloat this gem or creates the strain on resources for the end user. Please correct me if I'm wrong, but as of today if someone explicitly declares `exiftool` gem in their own Gemfile nothing breaks.
